core/apps/dashboard/urls.py
from django.urls import path
from order.models import Order , Orderproduct
from . import views


app_name = "profile"
urlpatterns = [
    path("",views.OrderPage,name="dashboard"),
    path("UpdateInfo/",views.UpdateInfo,name="Update-Info"),
    path("All-address/",views.AllAddressPage,name="All-Address"),
    path("Add-Address/",views.Add_Address,name="Add-Address"),
    path("Delete-Address/<pk>/",views.DeleteAddress,name="Delete-Address"),
    path("Update-Address/<pk>/",views.UpdateAddress,name="Update-Address"),
]

core/apps/order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns =[
    path("AddProductToOrder",views.AddProductToOrder,name="AddProduct"),
    path("OrderDetail/",views.OrederDetail,name="order-detail"),
    path("DeleteOrderProduct/<pk>/",views.DeleteOrederProduct,name="DeleteOrderProduct"),
]

core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('',include('product.urls')),
    path('admin/', admin.site.urls),
    path('Category/',include('category.urls')),
    path('Order/',include('order.urls')),
    path('Account/',include('authentication.urls')),
    path('dashboard/',include('dashboard.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/profile/_Card.html
<!-- Heading -->
<h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your Order's</span>
    <span class="badge badge-secondary badge-pill">{{orders.products.all.count}}</span>
</h4>

<!-- Cart -->
<ul class="list-group mb-3 z-depth-1">
    {% for item in orders.products.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
            <h6 class="my-0">{{item.product.title}}</h6>
            <small class="text-muted">count: {{item.quantity}}</small>
        </div>
        {% if item.get_total_discount_product_price %}
        <span class="text-muted text-danger">offer: -${{item.get_total_discount_product_price}}</span>
        {% endif %}
        <span class="text-muted">${{item.get_final_price}}</span>
        <span class="text-muted"><a class="btn btn-danger btn-sm"
                href="{% url 'order:DeleteOrderProduct' item.id %}">remove</a></span>
    </li>
    {% endfor %}

    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{orders.get_total}}</strong>
    </li>
</ul>
<!-- Cart -->

<!-- Promo code -->
<div class="card p-2">
    <div class="input-group">
        <a class="btn btn-block btn-secondary btn-md waves-effect m-12" type="button">Pay</a>
    </div>

</div>
<!-- Promo code -->

templates/components/profile/_slide.html
{% url 'profile:dashboard'  as dashboard %}
{% url 'profile:All-Address' as all_address %}
{% url "profile:Update-Info" as update_info %}

<div class="list-group">
    {% if request.path == dashboard %}
    <a href="{{dashboard}}" class="list-group-item list-group-item-action active">
        Detail Order
    </a>
    {% else %}
    <a href="{{dashboard}}" class="list-group-item list-group-item-action">
        Detail Order
    </a>
    {% endif %}

    {% if request.path == all_address %}
    <a href="{{all_address}}" class="list-group-item list-group-item-action active">
        My Addresses
    </a>
    {% else %}
    <a href="{{all_address}}" class="list-group-item list-group-item-action">
        Add Address Or Change To Default
    </a>
    {% endif %}

    {% if request.path == update_info %}
    <a href="{{update_info}}" class="list-group-item list-group-item-action active">
        Update My Information
    </a>
    {% else %}
    <a href="{{update_info}}" class="list-group-item list-group-item-action">
        Update My Information
    </a>
    {% endif %}


    <!-- <a href="#" class="list-group-item list-group-item-action">
        Change Password
    </a> -->

</div>