core/apps/product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns =[
    path("",views.ProductList,name='Home'),
    path("<int:page>/",views.ProductList,name='ProductList'),
    path("search/",views.SearchProduct,name='SearchProduct'),
    path("Detail/<slug>/",views.ProductDetail,name="product-detail"),
]

core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('',include('product.urls')),
    path('admin/', admin.site.urls),
    path('Category/',include('category.urls')),
    path('Order/',include('order.urls')),
    path('Account/',include('authentication.urls')),
    path('dashboard/',include('dashboard.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/Body/_card.html
<div class="card">
    <!--Card image-->
    <div class="view overlay">
        <img src="{{product.get_poster}}" class="card-img-top" alt="">
        <a>
            <div class="mask rgba-white-slight"></div>
        </a>
    </div>
    <!--Card image-->

    <!--Card content-->
    <div class="card-body text-center">
        <!--Category & Title-->
        <a href="" class="grey-text">
            <h5>{{ product.get_categories.first.title }}</h5>
        </a>
        <h5>
            <strong>
                <a href="" class="dark-grey-text">{{product.title}}
                    <span class="badge badge-pill danger-color">NEW</span>
                </a>
            </strong>
        </h5>

        <h4 class="font-weight-bold blue-text">
            <strong>{{product.price}}$</strong>
        </h4>

    </div>
    <!--Card content-->

</div>

templates/components/Body/_card_style_2.html
<!-- Card -->
<div class="card">

    <!-- Card image -->
    <div class="view overlay">
        <img class="card-img-top" src="{{product.get_poster}}" alt="Card image cap">
        <a href="{{product.get_absolute_url}}">
            <div class="mask rgba-white-slight"></div>
        </a>
    </div>

    <!-- Card content -->
    <div class="card-body">

        <p class="mb-1"><a href="{{product.get_absolute_url}}"
                class="font-weight-bold black-text">{{product.title|title}}</a>
        </p>

        <p class="mb-1"><small class="mr-1"><s>$299</s></small><strong>${{product.price}}</strong></p>

        <div class="amber-text fa-xs mb-1">
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
            <i class="far fa-star"></i>
        </div>

        <a href='{{product.get_absolute_url}}' class="btn btn-black btn-rounded btn-sm px-3">Buy Now</a>
    </div>

</div>
<!-- Card -->

templates/components/Body/_gallery.html
{% comment %}
<div class="row">
    <div class="col-3">
        <div class="view overlay rounded gallery-item hoverable">
            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12a.jpg" class="img-fluid">
            <div class="mask rgba-white-slight"></div>
        </div>
    </div>
    <div class="col-3">
        <div class="view overlay rounded gallery-item hoverable">
            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/13a.jpg" class="img-fluid">
            <div class="mask rgba-white-slight"></div>
        </div>
    </div>
    <div class="col-3">
        <div class="view overlay rounded gallery-item hoverable">
            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/14a.jpg" class="img-fluid">
            <div class="mask rgba-white-slight"></div>
        </div>
    </div>
    <div class="col-3">
        <div class="view overlay rounded gallery-item hoverable">
            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/15a.jpg" class="img-fluid">
            <div class="mask rgba-white-slight"></div>
        </div>
    </div>
</div>
{% endcomment %}
<div class="container">
    <div id="carouselGallery" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselGallery" data-slide-to="0" class="active bg-info"></li>
            <li data-target="#carouselGallery" data-slide-to="1" class="bg-info"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <div class="row p-2">
                    <div class="col-3">
                        <div class="view overlay rounded gallery-item hoverable">
                            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/15a.jpg"
                                class="img-fluid">
                            <div class="mask rgba-white-slight"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <div class="row p-2">
                    <div class="col-3">
                        <div class="view overlay rounded gallery-item hoverable">
                            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/15a.jpg"
                                class="img-fluid">
                            <div class="mask rgba-white-slight"></div>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselGallery" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon bg-info" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselGallery" role="button" data-slide="next">
                <span class="carousel-control-next-icon bg-info" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

templates/components/Body/_pagination.html
<nav class="d-flex justify-content-center wow fadeIn">
    <ul class="pagination pg-blue">

        <li class="page-item {{ products.has_previous|yesno:' ,disabled' }}">

            {% if products.has_previous %}
            <a class="page-link" href="{% url 'product:ProductList' products.previous_page_number %}"
                aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
            {% else %}
            <a class="page-link" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
            {% endif %}

        </li>
        {% for i in products.paginator.page_range %}
        {% if products.number == i %}
        <li class="page-item active">
            <a class="page-link" href="#">{{ i }}
                <span class="sr-only">(current)</span>
            </a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="{% url 'product:ProductList' i %}">{{ i }}</a>
        </li>

        {% endif %}
        {% endfor %}


        <li class="page-item {{ products.has_next|yesno:',disabled' }}">
            {% if products.has_next %}
            <a class="page-link" href="{% url 'product:ProductList' products.next_page_number %}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
            {% else %}
            <a class="page-link" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
            {% endif %}

        </li>

    </ul>
</nav>

templates/components/Body/_searchbox_nav.html
{% load category_tag %}
{% get_categories as categories %}

<nav class="navbar navbar-expand-lg navbar-dark mdb-color dark mt-3 mb-5">

    <!-- Navbar brand -->
    <span class="navbar-brand">Top Categories:</span>

    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">

            {% if request.path == "/" %}
            <li class="nav-item active">
                <a class="nav-link" href="/">First page
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="/">First page
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            {% endif %}

            {% for category in categories %}
            {% if request.path == category.get_absolute_url %}
            <li class="nav-item active">
                <a class="nav-link text" href="{{category.get_absolute_url}}">{{category.title}}</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link text" href="{{category.get_absolute_url}}">{{category.title}}</a>
            </li>
            {% endif %}

            {% endfor %}

        </ul>

        <form class="form-inline" action="{% url 'product:SearchProduct' %}">
            <div class="md-form my-0">
                <input class="form-control mr-sm-2" name="search" value="{{request.GET.search}}" type="text"
                    placeholder="Search" aria-label="Search">
            </div>
        </form>
    </div>
</nav>

templates/components/Body/_slider_product.html
<!-- https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/shoes%20(6).jpg -->
<div class="container">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            {% for count in counters %}
            <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}"
                class="{{forloop.first|yesno:'active, '}} bg-info"></li>
            {% endfor %}
        </ol>
        <div class="carousel-inner">

            {% for objects in list_objects %}
            <div class="carousel-item {{forloop.first|yesno:'active, '}}">
                <div class="row p-2">
                    {% for obj in objects  %}
                    <div class="col-lg-4 col-md-4 col-sm-12 mb-4">

                        <!-- Card -->
                        <div class="card">

                            <!-- Card image -->
                            <div class="view overlay">
                                <img class="card-img-top" src="{{obj.get_poster}}" alt="Card image cap">
                                <a href="#!">
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>

                            <!-- Card content -->
                            <div class="card-body">

                                <p class="mb-1"><a href="" class="font-weight-bold black-text">{{obj.title}}</a>
                                </p>

                                <p class="mb-1"><small class="mr-1"><s>$299</s></small><strong>${{obj.price}}</strong>
                                </p>

                                <div class="amber-text fa-xs mb-1">
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="far fa-star"></i>
                                </div>

                                <a type="button" class="btn btn-black btn-rounded btn-sm px-3">Buy Now</a>
                                <a type="button"
                                    class="btn btn-outline-black btn-rounded btn-sm px-3 waves-effect">Details</a>

                            </div>

                        </div>
                        <!-- Card -->


                    </div>
                    {% endfor %}
                </div>
            </div>

            {% endfor %}

        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon bg-info" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon bg-info" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>