core/apps/authentication/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path('login/',views.LoginPage,name="Login"),
    path("logout/",views.LogoutPage,name="Logout"),
    path("sign-up/",views.SignUpPage,name="SignUp"),
]

core/apps/dashboard/urls.py
from django.urls import path
from order.models import Order , Orderproduct
from . import views


app_name = "profile"
urlpatterns = [
    path("",views.OrderPage,name="dashboard"),
    path("UpdateInfo/",views.UpdateInfo,name="Update-Info"),
    path("All-address/",views.AllAddressPage,name="All-Address"),
    path("Add-Address/",views.Add_Address,name="Add-Address"),
    path("Delete-Address/<pk>/",views.DeleteAddress,name="Delete-Address"),
    path("Update-Address/<pk>/",views.UpdateAddress,name="Update-Address"),
]

core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('',include('product.urls')),
    path('admin/', admin.site.urls),
    path('Category/',include('category.urls')),
    path('Order/',include('order.urls')),
    path('Account/',include('authentication.urls')),
    path('dashboard/',include('dashboard.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/apps/slider/models.py
from django.db import models
import os

def get_file_ext(filepath):
    base_name = os.path.basename(filepath)
    name , ext = os.path.splitext(base_name)
    return  name , ext

def change_file_name(instance, filename):
    name,ext = get_file_ext(filename)
    new_name = f"SliderImage/{instance.id}-{instance.title}{ext}"
    return new_name



class Slider(models.Model):
    poster = models.ImageField(upload_to=change_file_name,default='image_default\default.jpg',verbose_name="پستر")
    title = models.CharField(max_length=100,blank=False,null=False,verbose_name="عنوان")
    detail = models.CharField(max_length=100,blank=False,null=False,verbose_name="جزئیات")
    description = models.TextField(verbose_name="توضیحات",null=False,blank=False)
    url = models.URLField(verbose_name="ادرس")
    title_url = models.CharField(max_length=30,blank=False,null=False,verbose_name="عنوان برای ادرس")
    
    def get_poster_url(self):
        return self.poster.url
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name="اسلاید"
        verbose_name_plural="اسلاید ها"

core/apps/slider/views.py
from django.shortcuts import render

# Create your views here.

templates/components/Header/_nav.html
{% load category_tag %}
{% get_categories as categories %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="/">
            <strong class="blue-text">Decode</strong>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link waves-effect" href="/">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="#">All Category</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Top Category
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for category in categories %}
                        <a class="dropdown-item" href="{{category.get_absolute_url}}">{{category.title}}</a>
                        {% endfor %}
                    </div>
                </li>
            </ul>

            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">


                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link waves-effect">
                        <span class="badge red z-depth-1 mr-1"> 1 </span>
                        <i class="fas fa-shopping-cart"></i>
                    </a>
                </li>
                <li class="nav-item mr-2">
                    <a href="{% url 'profile:dashboard'  %}" class="nav-link border border-light rounded waves-effect">
                        <i class="fas fa-user mr-2"></i>Dashboard
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'account:Logout'  %}" class="nav-link border border-light rounded waves-effect">
                        <i class="fas fa-sign-out-alt mr-2"></i>Logout
                    </a>
                </li>
                {% else %}
                <li class="nav-item mr-2">
                    <a href="{% url 'account:SignUp'  %}" class="nav-link border border-light rounded waves-effect">
                        <i class="fas fa-user-plus mr-2"></i>Sign-Up
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'account:Login'  %}" class="nav-link border border-light rounded waves-effect">
                        <i class="fas fa-sign-in-alt mr-2"></i>Sign-In
                    </a>
                </li>
                {% endif %}
            </ul>

        </div>

    </div>
</nav>

templates/components/Header/_slider.html
{% load slider_list %}

{% get_slider as sliders %}

<div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <ol class="carousel-indicators">
        {% for slide in sliders %}
        <li data-target="#carousel-example-1z" data-slide-to="{{forloop.counter}}"
            class="{{forloop.first|yesno:'active, '}}"></li>
        {% endfor %}

    </ol>

    <div class="carousel-inner" role="listbox">
        {% for slide in sliders %}
        <div class="carousel-item {{forloop.first|yesno:'active, '}}">
            <div class="view"
                style="background-image: url('{{slide.get_poster_url}}'); background-repeat: no-repeat; background-size: cover;">

                <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

                    <div class="text-center white-text mx-5 wow fadeIn">
                        <h1 class="mb-4">
                            <strong>{{slide.title}}</strong>
                        </h1>

                        <p>
                            <strong>{{slide.detail}}</strong>
                        </p>

                        <p class="mb-4 d-none d-md-block">
                            <strong>{{slide.description}}</strong>
                        </p>

                        <a target="_blank" href="{{slide.url}}" class="btn btn-outline-white btn-lg">
                            {{slide.title_url}}
                        </a>
                    </div>

                </div>

            </div>
        </div>
        {% endfor %}



    </div>

    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>