core/apps/address/urls.py
from django.urls import path

urlpatterns =[
    
]

core/apps/dashboard/urls.py
from django.urls import path
from order.models import Order , Orderproduct
from . import views


app_name = "profile"
urlpatterns = [
    path("",views.OrderPage,name="dashboard"),
    path("UpdateInfo/",views.UpdateInfo,name="Update-Info"),
    path("All-address/",views.AllAddressPage,name="All-Address"),
    path("Add-Address/",views.Add_Address,name="Add-Address"),
    path("Delete-Address/<pk>/",views.DeleteAddress,name="Delete-Address"),
    path("Update-Address/<pk>/",views.UpdateAddress,name="Update-Address"),
]

core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('',include('product.urls')),
    path('admin/', admin.site.urls),
    path('Category/',include('category.urls')),
    path('Order/',include('order.urls')),
    path('Account/',include('authentication.urls')),
    path('dashboard/',include('dashboard.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/apps/address/models.py
from django.db import models
from django.conf import settings

ADDRESS_CHOICES = (
    ('B', 'گیرنده'),
    ('S', 'فرستند(فروشگاه)'),
)

class AddressManager(models.Model):
    def get_default(self):
        return self.filter(default=True).first()

class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,verbose_name="کاربر")
    state_address = models.CharField(max_length=100,verbose_name="استان")
    city_address = models.CharField(max_length=100,verbose_name="شهر")
    detail_address = models.TextField(verbose_name="ادرس دقیق")
    zip_code = models.CharField(max_length=100,verbose_name="کد پستی")
    address_type = models.CharField(max_length=1,default="B",blank=True,null=True ,choices=ADDRESS_CHOICES,verbose_name="نوع ادرس")
    default = models.BooleanField(default=False,verbose_name="پیش فرض")

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name="ادرس"
        verbose_name_plural = 'ادرس ها'

core/apps/address/forms.py
from django import forms
from .models import Address

class AddressForm(forms.Form):
    user = forms.IntegerField(
        required=False,
        widget = forms.HiddenInput()
    )
    state_address = forms.CharField(
        required = True,
        widget = forms.TextInput(
            attrs={
                "class": "form-control",
                # "placeholder": "state"
            }
        )
    )
    city_address = forms.CharField(
        required = True,
        widget = forms.TextInput(
            attrs={
                "class": "form-control",
                # "placeholder": "city"
            }
        )
    )
    zip_code = forms.CharField(
        required = True,
        widget = forms.TextInput(
            attrs={
                "class": "form-control",
                # "placeholder": "zip code"
            }
        )
    )
    default = forms.BooleanField(
        widget = forms.CheckboxInput(
            attrs={
                "class": "form-check-input",
            }
        )
    )
    detail_address = forms.CharField(
        required=True,
        widget=forms.Textarea(
            attrs={
                "class":"form-control",
                "placeholder":"Address ",
                "rows":1,
            }
        )
    )
    
    def Save(self):
        all_data = self.cleaned_data()
        print(all_data)
    # def __init__(self,*args,**kwargs):
    #     super().__init__()
    #     print(self.fields['zip_code'])

class AddAddressForm(forms.ModelForm):

    class Meta:
        model = Address
        fields =[]
        widgets = {
            "user" : forms.HiddenInput(),
            "state_address":forms.TextInput(
            attrs={
                "class": "form-control",
                # "placeholder": "state"
                }
            ),
            "city_address":forms.TextInput(
            attrs={
                "class": "form-control",
                # "placeholder": "state"
                }
            ),
            "detail_address":forms.Textarea(
            attrs={
                "class":"form-control",
                "placeholder":"Address ",
                "rows":1,
            }
            ),
            "default":forms.CheckboxInput(
            attrs={
                "class": "form-check-input",
            }
            ),
            "zip_code":forms.TextInput(
            attrs={
                "class": "form-control",
                # "placeholder": "state"
                }
            ),
        }

core/apps/address/views.py
from django.shortcuts import render

# Create your views here.

# def AddAddress(request):
    

templates/address/All_address.html
{% extends "base/main.html" %}

{% block title %}profile-{{title}}{% endblock title %}


{% block style %}
<style type="text/css">
    /* Chart.js */
    @-webkit-keyframes chartjs-render-animation {
        from {
            opacity: 0.99
        }

        to {
            opacity: 1
        }
    }

    @keyframes chartjs-render-animation {
        from {
            opacity: 0.99
        }

        to {
            opacity: 1
        }
    }

    .chartjs-render-monitor {
        -webkit-animation: chartjs-render-animation 0.001s;
        animation: chartjs-render-animation 0.001s;
    }
</style>
{% endblock style %}

{% block main %}
<main class="mt-5 pt-4 pb-5">
    <div class="container wow fadeIn" style="visibility: visible; animation-name: fadeIn;">

        <!-- Heading -->
        <h2 class="my-5 h2 text-center">Profile</h2>

        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-lg-4 col-md-4 col-sm-12">
                <!-- Heading -->
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Your Profile</span>
                </h4>
                <!-- Cart -->
                {% include "components/profile/_slide.html" %}
                <!-- Cart -->
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-8 col-md-8 col-sm-12 mx-auto">
                <div class="card">
                    <div class="list-group d-inline">
                        {% for ads in address %}
                        <div class="list-group-item list-group-item-action">
                            <a href="{% url 'profile:Update-Address' ads.id %}"
                                class=" ">{{ads.state_address}}/{{ads.city_address}}/{{ads.detail_address}}
                                {% if ads.default %}
                                <i class="fas fa-check-square text-success float-right fa-lg"></i>
                                {% endif %}
                            </a>
                            <a class="btn btn-danger btn-sm" href="{% url 'profile:Delete-Address' ads.id %}">remove</a>
                        </div>

                        {% endfor %}
                        <a href="{% url 'profile:Add-Address' %}"
                            class="list-group-item list-group-item-action bg-warning text-white text-center"> <i
                                class="fas fa-plus"></i> Address
                        </a>
                    </div>
                </div>

            </div>
            <!--Grid column-->


        </div>
        <!--Grid row-->

    </div>
</main>
{% endblock main %}

{% block scripts %}
<script type="text/javascript">
    // Animations initialization
    new WOW().init();
</script>
{% endblock scripts %}

templates/address/address.html
{% extends "base/main.html" %}

{% block title %}profile-{{title}}{% endblock title %}


{% block style %}
<style type="text/css">
    /* Chart.js */
    @-webkit-keyframes chartjs-render-animation {
        from {
            opacity: 0.99
        }

        to {
            opacity: 1
        }
    }

    @keyframes chartjs-render-animation {
        from {
            opacity: 0.99
        }

        to {
            opacity: 1
        }
    }

    .chartjs-render-monitor {
        -webkit-animation: chartjs-render-animation 0.001s;
        animation: chartjs-render-animation 0.001s;
    }
</style>
{% endblock style %}

{% block main %}
<main class="mt-5 pt-4">
    <div class="container wow fadeIn" style="visibility: visible; animation-name: fadeIn;">

        <!-- Heading -->
        <h2 class="my-5 h2 text-center">Profile</h2>

        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-lg-4 col-md-4 col-sm-12">
                <!-- Heading -->
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Your Profile</span>
                </h4>
                <!-- Cart -->
                {% include "components/profile/_slide.html" %}
                <!-- Cart -->
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-8 col-md-8 col-sm-12 mx-auto">
                <div class="card">

                    <!--Card content-->
                    <form class="card-body" method="POST">
                        {% csrf_token %}

                        <!--Grid row-->
                        <div class="row">

                            <!--Grid column-->
                            <div class="col-md-6 mb-2">

                                <!--firstName-->
                                <div class="md-form ">
                                    <label for="{{form.state_address.id_for_label}}" class="">State</label>
                                    {{ form.state_address }}
                                </div>
                                {% for error in form.state_address.errors %}
                                <p class="text-danger">{{error}}</p>
                                {% endfor %}

                            </div>
                            <!--Grid column-->

                            <!--Grid column-->
                            <div class="col-md-6 mb-2">

                                <!--lastName-->
                                <div class="md-form">
                                    <label for="form.city_address.id_for_label" class="">City</label>
                                    {{form.city_address}}
                                </div>
                                {% for error in form.city_address.errors %}
                                <p class="text-danger">{{error}}</p>
                                {% endfor %}

                            </div>
                            <!--Grid column-->

                        </div>
                        <!--Grid row-->
                        <div class="row">
                            <!--Grid column-->
                            <div class="col-md-6 mb-2">
                                <!--lastName-->
                                <div class="md-form">
                                    <label for="form.zip_code.id_for_label" class="">Zip</label>
                                    {{form.zip_code}}
                                </div>
                                {% for error in form.zip_code.errors %}
                                <p class="text-danger">{{error}}</p>
                                {% endfor %}

                            </div>
                            <!--Grid column-->
                            <div class="col-md-6 mb-2 my-auto">
                                <div class="form-check">
                                    {{form.default}}
                                    <label class="form-check-label" for="{{form.default.id_for_label}}">
                                        Default Address
                                    </label>
                                </div>

                            </div>
                        </div>
                        <!--address-->
                        <div class="md-form mb-5">
                            {{form.detail_address}}
                        </div>
                        {% for error in form.detail_address.errors %}
                        <p class="text-danger">{{error}}</p>
                        {% endfor %}

                        <button class="btn btn-primary btn-lg btn-block waves-effect waves-light" type="submit">Continue
                            to checkout</button>
                        {{ form.user }}
                        {{ form.address_type }}
                    </form>

                </div>
            </div>
            <!--Grid column-->


        </div>
        <!--Grid row-->

    </div>
</main>
{% endblock main %}

{% block scripts %}
<script type="text/javascript">
    // Animations initialization
    new WOW().init();
</script>
{% endblock scripts %}